CREATE TABLE IF NOT EXISTS vehicles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    owner VARCHAR(50) NOT NULL,
    model VARCHAR(50) NOT NULL,
    engine_type VARCHAR(50) NOT NULL,
    hp INT NOT NULL,
    nm INT NOT NULL,
    capacity FLOAT NOT NULL,
    cylinders INT NOT NULL,
    pistons INT NOT NULL,
    camshafts INT NOT NULL,
    vMax FLOAT NOT NULL,
    engine_type_detail VARCHAR(50) NOT NULL,
    nitro BOOLEAN,
    stereo BOOLEAN,
    mk BOOLEAN,
    chip_tuning BOOLEAN,
    neons BOOLEAN,
    lamp_color VARCHAR(50),
    window_tint INT,
    lamp_type VARCHAR(50),
    brakes INT,
    suspension INT,
    bulletproof_windows BOOLEAN,
    bulletproof_tires BOOLEAN,
    armor INT,
    gearbox VARCHAR(50),
    turbo BOOLEAN,
    offroad BOOLEAN,
    handbrake_adjustment INT,
    rust_protection BOOLEAN,
    exhaust_system VARCHAR(50),
    brake_trail_color VARCHAR(50),
    safety_cage BOOLEAN,
    hood_scoops BOOLEAN,
    roof_scoops BOOLEAN,
    wheel_camber INT,
    rim_size INT,
    window_color VARCHAR(50),
    price INT
);
